### ISSUE TITLE
Add Availability Zones capabilities

### ISSUE THREAD

**Issue by mrclemensiii** [oraziobattaglia/terraform-azurerm-compute#2]
This is by far the best compute module on the registry.  Such a wonderful job and so easy to use.  Thank you very much.  One thing I would like to request is the ability to use availability zones instead of availability sets. 

I was able to hack the code to allow this capability for myself but its definitely not the best way to do this.  And you have to make sure the managed disks are created in the same zone in order to attach them to the VM.

Could you take a look at this as a possible enhancement request?

### new variable
variable "zones" {
  default = []
}

### Modification to VMs resource code
**Virtual machine Windows**
resource "azurerm_windows_virtual_machine" "vm-windows" {
  count                 = var.is_windows ? var.virtual_machine_instances : 0
  name                  = "${var.virtual_machine_names[count.index]}-vm"
  location              = var.location
  resource_group_name   = var.resource_group
  availability_set_id   = var.availability_set_enabled ? var.availability_set_id : null
  network_interface_ids = [azurerm_network_interface.nic[count.index].id]
  size                  = var.vm_size
  license_type          = var.license_type
  **zone                 = join(", ",[element(var.zones, count.index)])**

### Modification to the managed disk resource code
**Create optionals data disks**
resource "azurerm_managed_disk" "vm-data-disk" {
  count = length(local.vms_2_data_disks) > 0 ? length(local.vms_2_data_disks) : 0

  name                 = local.vms_2_data_disks[count.index].data_disk_name
  location             = var.location
  resource_group_name  = var.resource_group
  storage_account_type = local.vms_2_data_disks[count.index].data_disk_sa_type
  create_option        = "Empty"
  disk_size_gb         = local.vms_2_data_disks[count.index].data_disk_size_gb
  **zones = [element(var.zones, floor(count.index / length(var.data_disks)) )]**

  tags = var.tags
}

**Comment by oraziobattaglia** [comment]
Hi Melvin thank you very much for your feedback.
I'm just watching now at the availability zones, I never used them.

Let me understand better the scenario.
For example you want deploy 4 vm (vm1,vm2,vm3,vm4) with 2 disks each (disk1,disk2) in 2 availability zones (1,2) so the vm1 and its 2 disks will be on zone 1, the vm2 and its 2 disks will be on zone 2, the vm3 and its 2 disks will be on zone 1 and the vm4 and its 2 disks will be on zone 2?
If this is right I think your code will work, you used the element function to wrap around the index I think.

Two things I don't understand:
1. why the join function in the vm zone? For the vm it seems you can specify only one zone https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_virtual_machine
2. why the managed disk can have more the one zone?

I hope to find time soon to make the change and test it.
Bye

**Comment by mrclemensiii** [comment]
The scenario you listed is correct.  I found out the hard way that if a VM is created in Zone 1 any additional managed disk that is going to be attached must be in the same zone.

I used the join function as a hack because "zone" requires a string and I was providing an element from a list and I couldn't figure out how to make that work.  I am sure there is a better more correct way to implement this... I just couldn't figure it out.

**Comment by oraziobattaglia** [comment]
Hi Melvin, I added the possibility to use availability zones. It's possible to use availability zones: the vms and relevant data disks will be deployed in availability_zones_number zones, default to 3. The first vm and its data disks will be deployed on availability zone 1, the second vm and its data disks will be deployed on availability zone 2 and so on.
You cannot add further data disks to deployed vms, but this is an original limitation.
This feature is added to v0.6.5.
Let me know if this works as expected.
Bye
